<?php

use Illuminate\Database\Seeder;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('provincia')->insert([
            array('id' => '0101','nombre' => 'Chachapoyas','departamento_id' => '01'),
            array('id' => '0102','nombre' => 'Bagua','departamento_id' => '01'),
            array('id' => '0103','nombre' => 'Bongará','departamento_id' => '01'),
            array('id' => '0104','nombre' => 'Condorcanqui','departamento_id' => '01'),
            array('id' => '0105','nombre' => 'Luya','departamento_id' => '01'),
            array('id' => '0106','nombre' => 'Rodríguez de Mendoza','departamento_id' => '01'),
            array('id' => '0107','nombre' => 'Utcubamba','departamento_id' => '01'),
            array('id' => '0201','nombre' => 'Huaraz','departamento_id' => '02'),
            array('id' => '0202','nombre' => 'Aija','departamento_id' => '02'),
            array('id' => '0203','nombre' => 'Antonio Raymondi','departamento_id' => '02'),
            array('id' => '0204','nombre' => 'Asunción','departamento_id' => '02'),
            array('id' => '0205','nombre' => 'Bolognesi','departamento_id' => '02'),
            array('id' => '0206','nombre' => 'Carhuaz','departamento_id' => '02'),
            array('id' => '0207','nombre' => 'Carlos Fermín Fitzcarrald','departamento_id' => '02'),
            array('id' => '0208','nombre' => 'Casma','departamento_id' => '02'),
            array('id' => '0209','nombre' => 'Corongo','departamento_id' => '02'),
            array('id' => '0210','nombre' => 'Huari','departamento_id' => '02'),
            array('id' => '0211','nombre' => 'Huarmey','departamento_id' => '02'),
            array('id' => '0212','nombre' => 'Huaylas','departamento_id' => '02'),
            array('id' => '0213','nombre' => 'Mariscal Luzuriaga','departamento_id' => '02'),
            array('id' => '0214','nombre' => 'Ocros','departamento_id' => '02'),
            array('id' => '0215','nombre' => 'Pallasca','departamento_id' => '02'),
            array('id' => '0216','nombre' => 'Pomabamba','departamento_id' => '02'),
            array('id' => '0217','nombre' => 'Recuay','departamento_id' => '02'),
            array('id' => '0218','nombre' => 'Santa','departamento_id' => '02'),
            array('id' => '0219','nombre' => 'Sihuas','departamento_id' => '02'),
            array('id' => '0220','nombre' => 'Yungay','departamento_id' => '02'),
            array('id' => '0301','nombre' => 'Abancay','departamento_id' => '03'),
            array('id' => '0302','nombre' => 'Andahuaylas','departamento_id' => '03'),
            array('id' => '0303','nombre' => 'Antabamba','departamento_id' => '03'),
            array('id' => '0304','nombre' => 'Aymaraes','departamento_id' => '03'),
            array('id' => '0305','nombre' => 'Cotabambas','departamento_id' => '03'),
            array('id' => '0306','nombre' => 'Chincheros','departamento_id' => '03'),
            array('id' => '0307','nombre' => 'Grau','departamento_id' => '03'),
            array('id' => '0401','nombre' => 'Arequipa','departamento_id' => '04'),
            array('id' => '0402','nombre' => 'Camaná','departamento_id' => '04'),
            array('id' => '0403','nombre' => 'Caravelí','departamento_id' => '04'),
            array('id' => '0404','nombre' => 'Castilla','departamento_id' => '04'),
            array('id' => '0405','nombre' => 'Caylloma','departamento_id' => '04'),
            array('id' => '0406','nombre' => 'Condesuyos','departamento_id' => '04'),
            array('id' => '0407','nombre' => 'Islay','departamento_id' => '04'),
            array('id' => '0408','nombre' => 'La Uniòn','departamento_id' => '04'),
            array('id' => '0501','nombre' => 'Huamanga','departamento_id' => '05'),
            array('id' => '0502','nombre' => 'Cangallo','departamento_id' => '05'),
            array('id' => '0503','nombre' => 'Huanca Sancos','departamento_id' => '05'),
            array('id' => '0504','nombre' => 'Huanta','departamento_id' => '05'),
            array('id' => '0505','nombre' => 'La Mar','departamento_id' => '05'),
            array('id' => '0506','nombre' => 'Lucanas','departamento_id' => '05'),
            array('id' => '0507','nombre' => 'Parinacochas','departamento_id' => '05'),
            array('id' => '0508','nombre' => 'Pàucar del Sara Sara','departamento_id' => '05'),
            array('id' => '0509','nombre' => 'Sucre','departamento_id' => '05'),
            array('id' => '0510','nombre' => 'Víctor Fajardo','departamento_id' => '05'),
            array('id' => '0511','nombre' => 'Vilcas Huamán','departamento_id' => '05'),
            array('id' => '0601','nombre' => 'Cajamarca','departamento_id' => '06'),
            array('id' => '0602','nombre' => 'Cajabamba','departamento_id' => '06'),
            array('id' => '0603','nombre' => 'Celendín','departamento_id' => '06'),
            array('id' => '0604','nombre' => 'Chota','departamento_id' => '06'),
            array('id' => '0605','nombre' => 'Contumazá','departamento_id' => '06'),
            array('id' => '0606','nombre' => 'Cutervo','departamento_id' => '06'),
            array('id' => '0607','nombre' => 'Hualgayoc','departamento_id' => '06'),
            array('id' => '0608','nombre' => 'Jaén','departamento_id' => '06'),
            array('id' => '0609','nombre' => 'San Ignacio','departamento_id' => '06'),
            array('id' => '0610','nombre' => 'San Marcos','departamento_id' => '06'),
            array('id' => '0611','nombre' => 'San Miguel','departamento_id' => '06'),
            array('id' => '0612','nombre' => 'San Pablo','departamento_id' => '06'),
            array('id' => '0613','nombre' => 'Santa Cruz','departamento_id' => '06'),
            array('id' => '0701','nombre' => 'Prov. Const. del Callao','departamento_id' => '07'),
            array('id' => '0801','nombre' => 'Cusco','departamento_id' => '08'),
            array('id' => '0802','nombre' => 'Acomayo','departamento_id' => '08'),
            array('id' => '0803','nombre' => 'Anta','departamento_id' => '08'),
            array('id' => '0804','nombre' => 'Calca','departamento_id' => '08'),
            array('id' => '0805','nombre' => 'Canas','departamento_id' => '08'),
            array('id' => '0806','nombre' => 'Canchis','departamento_id' => '08'),
            array('id' => '0807','nombre' => 'Chumbivilcas','departamento_id' => '08'),
            array('id' => '0808','nombre' => 'Espinar','departamento_id' => '08'),
            array('id' => '0809','nombre' => 'La Convención','departamento_id' => '08'),
            array('id' => '0810','nombre' => 'Paruro','departamento_id' => '08'),
            array('id' => '0811','nombre' => 'Paucartambo','departamento_id' => '08'),
            array('id' => '0812','nombre' => 'Quispicanchi','departamento_id' => '08'),
            array('id' => '0813','nombre' => 'Urubamba','departamento_id' => '08'),
            array('id' => '0901','nombre' => 'Huancavelica','departamento_id' => '09'),
            array('id' => '0902','nombre' => 'Acobamba','departamento_id' => '09'),
            array('id' => '0903','nombre' => 'Angaraes','departamento_id' => '09'),
            array('id' => '0904','nombre' => 'Castrovirreyna','departamento_id' => '09'),
            array('id' => '0905','nombre' => 'Churcampa','departamento_id' => '09'),
            array('id' => '0906','nombre' => 'Huaytará','departamento_id' => '09'),
            array('id' => '0907','nombre' => 'Tayacaja','departamento_id' => '09'),
            array('id' => '1001','nombre' => 'Huánuco','departamento_id' => '10'),
            array('id' => '1002','nombre' => 'Ambo','departamento_id' => '10'),
            array('id' => '1003','nombre' => 'Dos de Mayo','departamento_id' => '10'),
            array('id' => '1004','nombre' => 'Huacaybamba','departamento_id' => '10'),
            array('id' => '1005','nombre' => 'Huamalíes','departamento_id' => '10'),
            array('id' => '1006','nombre' => 'Leoncio Prado','departamento_id' => '10'),
            array('id' => '1007','nombre' => 'Marañón','departamento_id' => '10'),
            array('id' => '1008','nombre' => 'Pachitea','departamento_id' => '10'),
            array('id' => '1009','nombre' => 'Puerto Inca','departamento_id' => '10'),
            array('id' => '1010','nombre' => 'Lauricocha ','departamento_id' => '10'),
            array('id' => '1011','nombre' => 'Yarowilca ','departamento_id' => '10'),
            array('id' => '1101','nombre' => 'Ica ','departamento_id' => '11'),
            array('id' => '1102','nombre' => 'Chincha ','departamento_id' => '11'),
            array('id' => '1103','nombre' => 'Nasca ','departamento_id' => '11'),
            array('id' => '1104','nombre' => 'Palpa ','departamento_id' => '11'),
            array('id' => '1105','nombre' => 'Pisco ','departamento_id' => '11'),
            array('id' => '1201','nombre' => 'Huancayo ','departamento_id' => '12'),
            array('id' => '1202','nombre' => 'Concepción ','departamento_id' => '12'),
            array('id' => '1203','nombre' => 'Chanchamayo ','departamento_id' => '12'),
            array('id' => '1204','nombre' => 'Jauja ','departamento_id' => '12'),
            array('id' => '1205','nombre' => 'Junín ','departamento_id' => '12'),
            array('id' => '1206','nombre' => 'Satipo ','departamento_id' => '12'),
            array('id' => '1207','nombre' => 'Tarma ','departamento_id' => '12'),
            array('id' => '1208','nombre' => 'Yauli ','departamento_id' => '12'),
            array('id' => '1209','nombre' => 'Chupaca ','departamento_id' => '12'),
            array('id' => '1301','nombre' => 'Trujillo ','departamento_id' => '13'),
            array('id' => '1302','nombre' => 'Ascope ','departamento_id' => '13'),
            array('id' => '1303','nombre' => 'Bolívar ','departamento_id' => '13'),
            array('id' => '1304','nombre' => 'Chepén ','departamento_id' => '13'),
            array('id' => '1305','nombre' => 'Julcán ','departamento_id' => '13'),
            array('id' => '1306','nombre' => 'Otuzco ','departamento_id' => '13'),
            array('id' => '1307','nombre' => 'Pacasmayo ','departamento_id' => '13'),
            array('id' => '1308','nombre' => 'Pataz ','departamento_id' => '13'),
            array('id' => '1309','nombre' => 'Sánchez Carrión ','departamento_id' => '13'),
            array('id' => '1310','nombre' => 'Santiago de Chuco ','departamento_id' => '13'),
            array('id' => '1311','nombre' => 'Gran Chimú ','departamento_id' => '13'),
            array('id' => '1312','nombre' => 'Virú ','departamento_id' => '13'),
            array('id' => '1401','nombre' => 'Chiclayo ','departamento_id' => '14'),
            array('id' => '1402','nombre' => 'Ferreñafe ','departamento_id' => '14'),
            array('id' => '1403','nombre' => 'Lambayeque ','departamento_id' => '14'),
            array('id' => '1501','nombre' => 'Lima ','departamento_id' => '15'),
            array('id' => '1502','nombre' => 'Barranca ','departamento_id' => '15'),
            array('id' => '1503','nombre' => 'Cajatambo ','departamento_id' => '15'),
            array('id' => '1504','nombre' => 'Canta ','departamento_id' => '15'),
            array('id' => '1505','nombre' => 'Cañete ','departamento_id' => '15'),
            array('id' => '1506','nombre' => 'Huaral ','departamento_id' => '15'),
            array('id' => '1507','nombre' => 'Huarochirí ','departamento_id' => '15'),
            array('id' => '1508','nombre' => 'Huaura ','departamento_id' => '15'),
            array('id' => '1509','nombre' => 'Oyón ','departamento_id' => '15'),
            array('id' => '1510','nombre' => 'Yauyos ','departamento_id' => '15'),
            array('id' => '1601','nombre' => 'Maynas ','departamento_id' => '16'),
            array('id' => '1602','nombre' => 'Alto Amazonas ','departamento_id' => '16'),
            array('id' => '1603','nombre' => 'Loreto ','departamento_id' => '16'),
            array('id' => '1604','nombre' => 'Mariscal Ramón Castilla ','departamento_id' => '16'),
            array('id' => '1605','nombre' => 'Requena ','departamento_id' => '16'),
            array('id' => '1606','nombre' => 'Ucayali ','departamento_id' => '16'),
            array('id' => '1607','nombre' => 'Datem del Marañón ','departamento_id' => '16'),
            array('id' => '1608','nombre' => 'Putumayo','departamento_id' => '16'),
            array('id' => '1701','nombre' => 'Tambopata ','departamento_id' => '17'),
            array('id' => '1702','nombre' => 'Manu ','departamento_id' => '17'),
            array('id' => '1703','nombre' => 'Tahuamanu ','departamento_id' => '17'),
            array('id' => '1801','nombre' => 'Mariscal Nieto ','departamento_id' => '18'),
            array('id' => '1802','nombre' => 'General Sánchez Cerro ','departamento_id' => '18'),
            array('id' => '1803','nombre' => 'Ilo ','departamento_id' => '18'),
            array('id' => '1901','nombre' => 'Pasco ','departamento_id' => '19'),
            array('id' => '1902','nombre' => 'Daniel Alcides Carrión ','departamento_id' => '19'),
            array('id' => '1903','nombre' => 'Oxapampa ','departamento_id' => '19'),
            array('id' => '2001','nombre' => 'Piura ','departamento_id' => '20'),
            array('id' => '2002','nombre' => 'Ayabaca ','departamento_id' => '20'),
            array('id' => '2003','nombre' => 'Huancabamba ','departamento_id' => '20'),
            array('id' => '2004','nombre' => 'Morropón ','departamento_id' => '20'),
            array('id' => '2005','nombre' => 'Paita ','departamento_id' => '20'),
            array('id' => '2006','nombre' => 'Sullana ','departamento_id' => '20'),
            array('id' => '2007','nombre' => 'Talara ','departamento_id' => '20'),
            array('id' => '2008','nombre' => 'Sechura ','departamento_id' => '20'),
            array('id' => '2101','nombre' => 'Puno ','departamento_id' => '21'),
            array('id' => '2102','nombre' => 'Azángaro ','departamento_id' => '21'),
            array('id' => '2103','nombre' => 'Carabaya ','departamento_id' => '21'),
            array('id' => '2104','nombre' => 'Chucuito ','departamento_id' => '21'),
            array('id' => '2105','nombre' => 'El Collao ','departamento_id' => '21'),
            array('id' => '2106','nombre' => 'Huancané ','departamento_id' => '21'),
            array('id' => '2107','nombre' => 'Lampa ','departamento_id' => '21'),
            array('id' => '2108','nombre' => 'Melgar ','departamento_id' => '21'),
            array('id' => '2109','nombre' => 'Moho ','departamento_id' => '21'),
            array('id' => '2110','nombre' => 'San Antonio de Putina ','departamento_id' => '21'),
            array('id' => '2111','nombre' => 'San Román ','departamento_id' => '21'),
            array('id' => '2112','nombre' => 'Sandia ','departamento_id' => '21'),
            array('id' => '2113','nombre' => 'Yunguyo ','departamento_id' => '21'),
            array('id' => '2201','nombre' => 'Moyobamba ','departamento_id' => '22'),
            array('id' => '2202','nombre' => 'Bellavista ','departamento_id' => '22'),
            array('id' => '2203','nombre' => 'El Dorado ','departamento_id' => '22'),
            array('id' => '2204','nombre' => 'Huallaga ','departamento_id' => '22'),
            array('id' => '2205','nombre' => 'Lamas ','departamento_id' => '22'),
            array('id' => '2206','nombre' => 'Mariscal Cáceres ','departamento_id' => '22'),
            array('id' => '2207','nombre' => 'Picota ','departamento_id' => '22'),
            array('id' => '2208','nombre' => 'Rioja ','departamento_id' => '22'),
            array('id' => '2209','nombre' => 'San Martín ','departamento_id' => '22'),
            array('id' => '2210','nombre' => 'Tocache ','departamento_id' => '22'),
            array('id' => '2301','nombre' => 'Tacna ','departamento_id' => '23'),
            array('id' => '2302','nombre' => 'Candarave ','departamento_id' => '23'),
            array('id' => '2303','nombre' => 'Jorge Basadre ','departamento_id' => '23'),
            array('id' => '2304','nombre' => 'Tarata ','departamento_id' => '23'),
            array('id' => '2401','nombre' => 'Tumbes ','departamento_id' => '24'),
            array('id' => '2402','nombre' => 'Contralmirante Villar ','departamento_id' => '24'),
            array('id' => '2403','nombre' => 'Zarumilla ','departamento_id' => '24'),
            array('id' => '2501','nombre' => 'Coronel Portillo ','departamento_id' => '25'),
            array('id' => '2502','nombre' => 'Atalaya ','departamento_id' => '25'),
            array('id' => '2503','nombre' => 'Padre Abad ','departamento_id' => '25'),
            array('id' => '2504','nombre' => 'Purús','departamento_id' => '25')
        ]);
    }
}
