<?php

use Illuminate\Database\Seeder;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('provincia')->insert([
            array('nombre' => 'Chachapoyas','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Bagua','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Bongará','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Condorcanqui','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Luya','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Rodríguez de Mendoza','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Utcubamba','departamento_id' => 1, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huaraz','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Aija','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Antonio Raymondi','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Asunción','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Bolognesi','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Carhuaz','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Carlos Fermín Fitzcarrald','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Casma','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Corongo','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huari','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huarmey','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huaylas','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Mariscal Luzuriaga','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ocros','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pallasca','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pomabamba','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Recuay','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Santa','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sihuas','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Yungay','departamento_id' => 2, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Abancay','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Andahuaylas','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Antabamba','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Aymaraes','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cotabambas','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chincheros','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Grau','departamento_id' => 3, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Arequipa','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Camaná','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Caravelí','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Castilla','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Caylloma','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Condesuyos','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Islay','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'La Uniòn','departamento_id' => 4, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huamanga','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cangallo','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huanca Sancos','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huanta','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'La Mar','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lucanas','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Parinacochas','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pàucar del Sara Sara','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sucre','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Víctor Fajardo','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Vilcas Huamán','departamento_id' => 5, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cajamarca','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cajabamba','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Celendín','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chota','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Contumazá','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cutervo','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Hualgayoc','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Jaén','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Ignacio','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Marcos','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Miguel','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Pablo','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Santa Cruz','departamento_id' => 6, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Prov. Const. del Callao','departamento_id' => 7, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cusco','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Acomayo','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Anta','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Calca','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Canas','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Canchis','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chumbivilcas','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Espinar','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'La Convención','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Paruro','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Paucartambo','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Quispicanchi','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Urubamba','departamento_id' => 8, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huancavelica','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Acobamba','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Angaraes','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Castrovirreyna','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Churcampa','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huaytará','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tayacaja','departamento_id' => 9, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huánuco','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ambo','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Dos de Mayo','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huacaybamba','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huamalíes','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Leoncio Prado','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Marañón','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pachitea','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Puerto Inca','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lauricocha ','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Yarowilca ','departamento_id' => 10, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ica ','departamento_id' => 11, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chincha ','departamento_id' => 11, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Nasca ','departamento_id' => 11, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Palpa ','departamento_id' => 11, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pisco ','departamento_id' => 11, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huancayo ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Concepción ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chanchamayo ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Jauja ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Junín ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Satipo ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tarma ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Yauli ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chupaca ','departamento_id' => 12, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Trujillo ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ascope ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Bolívar ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chepén ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Julcán ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Otuzco ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pacasmayo ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pataz ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sánchez Carrión ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Santiago de Chuco ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Gran Chimú ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Virú ','departamento_id' => 13, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chiclayo ','departamento_id' => 14, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ferreñafe ','departamento_id' => 14, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lambayeque ','departamento_id' => 14, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lima ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Barranca ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cajatambo ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Canta ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Cañete ','departamento_Aid' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huaral ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huarochirí ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huaura ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Oyón ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Yauyos ','departamento_id' => 15, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Maynas ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Alto Amazonas ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Loreto ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Mariscal Ramón Castilla ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Requena ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ucayali ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Datem del Marañón ','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Putumayo','departamento_id' => 16, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tambopata ','departamento_id' => 17, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Manu ','departamento_id' => 17, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tahuamanu ','departamento_id' => 17, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Mariscal Nieto ','departamento_id' => 18, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'General Sánchez Cerro ','departamento_id' => 18, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ilo ','departamento_id' => 18, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Pasco ','departamento_id' => 19, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Daniel Alcides Carrión ','departamento_id' => 19, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Oxapampa ','departamento_id' => 19, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Piura ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Ayabaca ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huancabamba ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Morropón ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Paita ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sullana ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Talara ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sechura ','departamento_id' => 20, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Puno ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Azángaro ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Carabaya ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Chucuito ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'El Collao ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huancané ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lampa ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Melgar ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Moho ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Antonio de Putina ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Román ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Sandia ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Yunguyo ','departamento_id' => 21, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Moyobamba ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Bellavista ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'El Dorado ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Huallaga ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Lamas ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Mariscal Cáceres ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Picota ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Rioja ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'San Martín ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tocache ','departamento_id' => 22, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tacna ','departamento_id' => 23, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Candarave ','departamento_id' => 23, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Jorge Basadre ','departamento_id' => 23, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tarata ','departamento_id' => 23, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Tumbes ','departamento_id' => 24, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Contralmirante Villar ','departamento_id' => 24, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Zarumilla ','departamento_id' => 24, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Coronel Portillo ','departamento_id' => 25, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Atalaya ','departamento_id' => 25, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Padre Abad ','departamento_id' => 25, 'pais_id' => 1, 'estado' => true),
            array('nombre' => 'Purús','departamento_id' => 25, 'pais_id' => 1, 'estado' => true)
        ]);
    }
}
